### ISSUE TITLE
Queries while installation

### ISSUE THREAD

**Issue by niyazafazl** [PSPDFKit/Cordova-Android#1]
The Read me document is very elaborative and easy to understand.
Iam using this kit for my Andriod Phonegap App, cordova version is 5.0.0 and my android platform is 4.0.0.

I have few doubts while installing this:
1. Your app's package name (in the above example com.example.pdfapp) has to match your PSPDFKit license name or PSPDFKit will throw an exception.
- where I can find the "PSPDFKit license name" or how I would verify that is same as app's package name.

2. Place your PSPDFKit library aar file into the `platforms/android/libs/` directory of your project.
- I can't find the "pspdfkit-1.2.2.aar" file in my project or where I could get that library file.

3. Regarding this line-  Configure your PSPDFKit license key inside the platforms/android/AndroidManifest: 

I have placed this line 
meta-data name="PSPDFKIT_LICENSE_KEY"

       <application 
    	android:hardwareAccelerated="true" 
    	android:icon="@drawable/icon" 
    	android:label="@string/app_name" 
    	android:supportsRtl="true">
        <activity 
        	android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale" 
        	android:label="@string/activity_name" 
        	android:launchMode="singleTop" 
        	android:name="MainActivity" 
        	android:theme="@android:style/Theme.Black.NoTitleBar" 
        	android:windowSoftInputMode="adjustResize">
            <intent-filter android:label="@string/launcher_name">
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <activity android:name="com.pspdfkit.ui.PSPDFKitActivity" android:windowSoftInputMode="adjustNothing" />
        <activity android:name="com.pspdfkit.ui.PSPDFKitAppCompatActivity" android:windowSoftInputMode="adjustNothing" />
        <meta-data name="PSPDFKIT_LICENSE_KEY">
    </application>

inside the AndroidManifest.xml file

Is this correct or do I want to configure something for the license key.

Please help to clarify the above. I am looking forward for your response for my installation. 

Thanks and much appreciated!

**Comment by steipete** [comment]
Thanks!

PSPDFKit is a commercial PDF framework. Start the process of licensing it via contacting sales via our website. Ultimately you'll buy one or more licenses (one license per bundle ID).

The aar file is part of the demo you get when you click Try Now on pspdfkit.com.

Please try that and we'll help you further with technical questions over at support.pspdfkit.com.
