### ISSUE TITLE
annotationEditoringConfiguration Error

### ISSUE THREAD

**Issue by bubbsi** [PSPDFKit/Cordova-Android#10]
Hello,

while compiling the app with the ionic framework and the PSPDFKIT Version 3.1.0 the java class PSPDFKitCordovaPlugin.java returns multiple errors. The first was the annotationEditoringConfiguration Error. By researching I found out, that this function was removed while the change from Version 3.0.0 to 3.1.0. 

For my first conclusion I uncommented the affected code. But while execution the app on an android smartphone I got the following error: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ionicframework.loboapp623542/com.pspdfkit.ui.PdfActivity}: android.view.InflateException: Binary XML file line #36: Error inflating class com.pspdfkit.ui.forms.FormEditingBar

**Comment by davidschreiber** [comment]
Hello @bubbsi! Thanks for the report. We have just updated the plugin code for PSPDFKit 3.1.0 for Android which resolves your issue. If you have any other questions or issues, please let us know. Thanks!
