### ISSUE TITLE
Problem Integrating the cordova-Android for PSPDFkit

### ISSUE THREAD

**Issue by midhunkrishnakv** [PSPDFKit/Cordova-Android#13]
Hi,
I am trying to integrate the cordova PSPFKIT plugin for my hybrid application.

I have done the below

Added https://github.com/PSPDFKit/Cordova-Android.git plugin to my project

Copied pspdfkit-3.1.1.aar under platforms/android/libs/

Set min sdk to 16

Added my demo license key to AndroidManifest.xml

Added a pdf file "myFile.pdf" under "www/documents"

Added the below under onDeviceReady method in index.js

 PSPDFKit.showDocumentFromAssets('www/documents/myFile.pdf', {
            title: 'My PDF Document',           
            scrollDirection: PSPDFKit.PageScrollDirection.VERTICAL,
            scrollMode: PSPDFKit.ScrollMode.CONTINUOUS,
            useImmersiveMode: true
        });
The application is loaded with no errors but the pdf file is not displayed.

**Comment by steipete** [comment]
Please update to our 3.2 release and try again. https://pspdfkit.com/changelog/android/

**Comment by midhunkrishnakv** [comment]
ok but how can i update to 3.2 release. Please.

**Comment by steipete** [comment]
Download here: https://pspdfkit.com/try/

**Comment by juliangrosshauser** [comment]
@midhunkrishnakv: Does your app work with the newest PSPDFKit version?

**Comment by radazzouz** [comment]
Is this still an issue in version 3.2.1? I used the sample code that you've sent us, the app launches and I can see the PDF document displayed properly.

I am closing this issue, but feel free to followup in here should you have any other questions.

Thanks!
