### ISSUE TITLE
Android Build issue with pspdf

### ISSUE THREAD

**Issue by firozcitrus** [PSPDFKit/Cordova-Android#16]
Hi ,
   I am integrating  cordova-android pspdf 3.2 kit   add key values in manifest file. Then trying to build using cordova shows `Attribute meta-data#android.support.VERSION@value value=(25.3.1) from [com.android.support:cardview-v7:25.3.1] AndroidManifest.xml:24:9-31
	is also present at [com.android.support:support-v4:26.0.0-alpha1] AndroidManifest.xml:27:9-38 value=(26.0.0-alpha1).
	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:22:5-24:34 to override.` error.

I am update my android sdk manager api versions (21,22,23,24,25,26). and also update Android Supporting Repository still same error occur. 
cordova version is 6.5.0.  if i remove pspdf kit and Supporting files then build worke . So Any idea about how to solve this.

Thanku.

**Comment by radazzouz** [comment]
@firozcitrus, Can you double-check the value for `android-minSdkVersion` in your`config.xml`? It should be 16.

**Comment by firozcitrus** [comment]
Solved error with edit platform/android/project.properties files with change 
`cordova.system.library.1=com.android.support:support-v4+` to `cordova.system.library.1=com.android.support:support-v4:25.3.1 `   .

In your pspdfkit.gradle file dependencies support version is  `com.android.support:support-v4:25.3.1` .
After fix this another error shows ,error is 
`FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexIndexOverflowException: method ID not in [0, 0xffff]: 65536`

We fix this error wit add  `multiDexEnabled true`  in platform/android/build.gradle  `defaultConfig ` and add `com.android.support:multidex:1.0.1` in platform/android/project.properties .After this work successfully .

**Comment by radazzouz** [comment]
That's great! Thanks for sharing your solution here.

I’m going ahead and close this issue. Please feel free to follow up here or open a new request if you have any other questions.
