### ISSUE TITLE
PSPDFkit cordova-Android 3.2  not working

### ISSUE THREAD

**Issue by firozcitrus** [PSPDFKit/Cordova-Android#17]
Hi ,
Integerating 3.2 version and add view code like this
`PSPDFKit.showDocumentFromAssets('www/documents/myFile.pdf', {
title: 'My PDF Document',
scrollDirection: PSPDFKit.PageScrollDirection.VERTICAL,
scrollMode: PSPDFKit.ScrollMode.CONTINUOUS,
useImmersiveMode: true
},function(success) { console.log("success");},function(error){console.log("error",error)});`

And also try

` PSPDFKit.showDocument(filePath, {
                    scrollDirection: PSPDFKit.PageScrollDirection.VERTICAL,
                    scrollMode: PSPDFKit.ScrollMode.CONTINUOUS,
                    useImmersiveMode: true
                },function(success){ console.log("success")},function(err){ console.log("errorrr",err)});`

filepath is local sdcard file url. The application is loaded with no errors but the pdf file is not displayed.
All the pspdf setting are Done. Can't identify what is the issue.

**Comment by firozcitrus** [comment]
Allready posted this issue in [](https://github.com/PSPDFKit/Cordova-Android/issues/13)

**Comment by radazzouz** [comment]
Glad to see you've sorted it out. Thanks for sharing! 👍
