### ISSUE TITLE
Inconsistent documentation

### ISSUE THREAD

**Issue by somethingquitecool** [PSPDFKit/Cordova-Android#2]
Hey,

When going through the steps to setup this plugin, I noticed a few inconsistencies. First, 

> Set the minimum SDK version of your Android application to 15.

Should be changed to 16.

Next, `PageScrollMode` in the doc is not consistent with `ScrollMode` found in [PSPDFKit.js](https://github.com/PSPDFKit/Cordova-Android/blob/master/www/PSPDFKit.js#L47)

**Comment by davidschreiber** [comment]
Thanks @somethingquitecool for reporting this! The inconsistencies have been fixed.
