### ISSUE TITLE
pdf not editable if editing password is set on it, android-cordova

### ISSUE THREAD

**Issue by raju1979** [PSPDFKit/Cordova-Android#20]
Hi,
I have successfully integrate the android-cordova plugin in my ionic 3 app. I slightly modified the plugin so that I can programatically send pdf open password when invocating the cordova plugin.
The pdf also has editing password set on it.  But PsPDFkit does not ask for editing password and I am unable to edit the pdf.

**Comment by steipete** [comment]
Hi! We currently don't support changing capabilities with the same document instance for a different password. Dismiss the view and re-show it with the other password to perform the capability-switch.

Please submit further questions via https://pspdfkit.com/support/request
