### ISSUE TITLE
Unable to import the PSPDFKit in Ionic (android) project

### ISSUE THREAD

**Issue by reverie-ss** [PSPDFKit/Cordova-Android#31]
I have done all the steps mentioned in the documentation page.
But am unable to import the *PSPDFKit* used in the below code

`function showMyDocument() {
	PSPDFKit.showDocumentFromAssets('www/documents/myFile.pdf', {
		title: 'My PDF Document',
		page: 4,
		scrollDirection: PSPDFKit.PageScrollDirection.VERTICAL,
		scrollMode: PSPDFKit.ScrollMode.CONTINUOUS,
		useImmersiveMode: true,
		password: "my-document-password"
	});
}`

**Comment by madhumatip** [comment]
hi,
i am facing the same issue i tried to build the app still it giving me the same error
typescript: src/pages/home/home.ts, line: 18
[18:39:02]  typescript: src/pages/home/home.ts, line: 19
[18:39:02]  ionic-app-script task: "build"
[18:39:02]  Error: Failed to transpile program
Error: Failed to transpile program
