### ISSUE TITLE
Crashed when zoom-in frequently

### ISSUE THREAD

**Issue by ArjunJadav** [PSPDFKit/Cordova-Android#33]
java.lang.IllegalArgumentException: pointerIndex out of range
        at android.view.MotionEvent.nativeGetAxisValue(Native Method)

   com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2403)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1737)

**Comment by radazzouz** [comment]
@ArjunJadav,

Can you please give us more context about this issue?

Unfortunately, we don't have enough information to help.

Please reach out to our support portal at pspdfkit.com/support/request/ - we're happy to provide support there for our commercial SDK. Also, please take a look our [Bug Reporting](https://pspdfkit.com/guides/android/current/troubleshooting/bug-reporting/) article.

Thank you!
