### ISSUE TITLE
no such file or directory: platforms/android/src/io/ionic/starter/*.java

### ISSUE THREAD

**Issue by madhumatip** [PSPDFKit/Cordova-Android#34]

**Comment by radazzouz** [comment]
Hi @madhumatip,

Thanks for reaching out to us!

Can you please give more details about this issue? Like when did it occur? At which step of the integration process did it fail.

Thank you!

**Comment by madhumatip** [comment]
thanks for replying me so fast..
i perform all the steps and when i tried to build my app with command ionic cordova build android it gives me error like this:

no such file or directory: platforms/android/src/io/ionic/starter/*.java
No Java files found that extend CordovaActivity.
[ERROR] An error occurred while running subprocess cordova.

        cordova build android exited with exit code 1.
