### ISSUE TITLE
open pdf from url cordova android

### ISSUE THREAD

**Issue by zyzekn** [PSPDFKit/Cordova-Android#41]
Hello
I've embedded your plug-in in my Cordoba-Android app, and it's really great.
My problem is that I have only 2 functions to open a PDF file.
One from the device itself, and the other through the ASSET.

How do I open a PDF file located at an external URL?
Such as:
http://www.pdf995.com/samples/pdf.pdf

Thanks in advance.

**Comment by radazzouz** [comment]
@zyzekn,

PSPDFKit works best with PDF documents on the local file system of your device. If you're looking into opening a PDF from a remote URL, we recommend that you download it first. You can use a plugin to download the PDF document.

For more information, please take a look at our documentation here: https://pspdfkit.com/guides/android/current/miscellaneous/document-downloads/

Thank you!
