### ISSUE TITLE
Quickstart-Guide: platforms/android/local.properties doesn't exist

### ISSUE THREAD

**Issue by KatGr** [PSPDFKit/Cordova-Android#43]
Hello,
I try to set up pspdfkit with Cordova-Android.

First I tried to get the demo(Guickstart-Guide) running but I don't have any local.properties file.
 I have a project.properties file within platforms/android but if I set pspdfkit.password=xyz I get : PSPDFKit password was not specified.

I am using cordova 8.1.2.

**Comment by davidschreiber** [comment]
Hi there, the properties have to be specified inside the `local.properties` file, not the `project.properties` file (which is something different). If you don't have such a file yet, you will need to create it first. Usually, triggering a build should also create this file for you.

In general, with technical questions please reach out to us via our technical support platform at https://pspdfkit.com/support/request/. Our team there will help you right away (and usually faster than here on GitHub). The issue tracker on GitHub is mostly for bug reports. Thanks!
