### ISSUE TITLE
Issue with loading PDF from sdCard

### ISSUE THREAD

**Issue by dpz3579** [PSPDFKit/Cordova-Android#6]
I'm trying this in **ionic.**

My code snippet is as follows

I tried to load the file present in my downloads folder in sdcard.

```
var uri = cordova.file.externalRootDirectory+'Download/relativity.pdf';

var options = {
    title: 'My PDF Document',
    scrollDirection: PSPDFKit.PageScrollDirection.VERTICAL,
    scrollMode: PSPDFKit.ScrollMode.CONTINUOUS,
    useImmersiveMode: true
};

PSPDFKit.showDocument('uri', options, function (success) {
    console.log("success");
}, function (failed) {
    console.log("failed");
});
```

I'm not getting the success callback neither error callback,
can you please check & let me know if i'm getting something wrong.

**P.S.** - _I used the aar file that was provided in the demo application, & it's respective Key._

**Comment by izacus** [comment]
Can you please also post a logcat output and the version of ionic/PSPDFKit/Android you're using to test the issue?

**Comment by davidschreiber** [comment]
@dpz3579 any updates on this? Closing it, but feel free to ping us in case you need further help.
